apiVersion: apps/v1
kind: Deployment                                          
metadata:
  name: maven-app
spec:
  selector:
    matchLabels:
      app: maven-app
  replicas: 2                                             
  minReadySeconds: 15
  strategy:
    type: RollingUpdate                                   
    rollingUpdate: 
      maxUnavailable: 1                                   
      maxSurge: 1                                         
  template:                                               
    metadata:
      labels:
        app: maven-app                                  
    spec:
      containers:
        - image: mamicheck/maven-app:maven-app
          imagePullPolicy: Always                         
          name: sa-frontend
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: maven-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8085
  selector:
    app: maven-app